version: '3.9'
services:
   nginx:
    image: nginx:latest
    container_name: 'nginx-cont'
    ports:
     - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - three-tier

   backend:
    build: ./backend
    container_name: 'node-cont'
    ports:
     - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017/userdata?authSource=admin
    networks:
      - three-tier

   mongo:
    image: mongo:latest
    container_name: 'mongo-cont'
    ports:
     - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db
    networks:
      - three-tier


volumes:
  mongo_data:

networks:
  three-tier:
